# Setup
title:               Hazards of the Present Day
tagline:             ''
description:         'A trial notebook'
url:                 https://hazardsofthepresentday.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kimberley Bayer
  url:               https://twitter.com/kimberley_bayer
  email:             

# Gems
plugins:
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-seo-tag

# Google Analytics
google_analytics_id: #UA-XXXX-Y

# Options
relative_links:
  enabled:     true
  collections: true 

# Custom vars
version:             2.1.0
